### ISSUE TITLE
INFO - Duplicate High Severity Vulnerability?

### ISSUE THREAD

**Issue by Sunoo** [autovance/ftp-srv#216]
Dependabot notified me of a high severity security vulnerability a few weeks ago in prior versions of this package, so I updated my dependency and moved on.

However, today I got a notification of what, to my eye, seems to be the same vulnerability, but now saying all versions are impacted and there is no fix available: https://github.com/advisories/GHSA-r4m5-47cq-6qg8

Even more confusing, the referenced NPM advisory says the remediation is to update to v4.3.4 or later: https://www.npmjs.com/advisories/1445

I’m hoping someone involved in this project can confirm whether this is an active problem with current versions or not.

**Comment by forstermatth** [comment]
This is a duplicate vulnerability that was published by their automated systems, based on the NPM vulnerability __before it was updated__. Some sort of lag in their sync process I am assuming. I opened a ticket on Friday notifying GitHub that the SA was invalid and needs to be removed.

The fix is available and is addressed here: https://github.com/autovance/ftp-srv/security/advisories/GHSA-jw37-5gqr-cf9j

I'm going to lock this convo, but keep the issue open and pin it until they resolve the duplicate entry in some way.

**Comment by forstermatth** [comment]
Github has withdrawn the duplicate advisory and this should not be a problem anymore.

**Comment by dimdenGD** [comment]
It seems that this was fixed a long time ago but when you install package with npm it still displays 1 High vulnerability:  
![vuln](https://lune.dimden.dev/e77999286b.png)  
It took me some time to find that this is just a bug in reporting system and I was considering changing package until finally found this issue. I don't know how these vulnerability reports work but you should try removing it from database somehow or add info to it, if possible.
