### ISSUE TITLE
on STOR, get filePath

### ISSUE THREAD

**Issue by DiegoRBaquero** [autovance/ftp-srv#90]
When a user uploads a file to a dir, STOR just gives the name and not the full path, which would then require to traverse all the dirs.

It would be nice to get the full path of the file that was just uploaded

**Comment by trs** [comment]
I think this would be a great improvement.
PRs welcome if you get around to this.

**Comment by DiegoRBaquero** [comment]
got it with const filePath = path.join(connection.fs.root, connection.fs.cwd, fileName). Will PR soon!

**Comment by trs** [comment]
We need to make sure the client is getting the correct path.

The client does not know about their `root`, to them, it is `/`. So we need to ensure we give them what they expect.

So, if `root = /my/root/path/` and `cwd = cur/dir`. If we `STOR` `file.txt`, the client's path is `/cur/dir/file.txt`, while the server's path is `/my/root/path/cur/dir/file.txt`.

The `STOR` event can get the full server path with the root.

**Comment by DiegoRBaquero** [comment]
I'm a bit lost. The STOR event happens in the server, so we need the path with root, cwd, and file. Which is what I'm joining together, to then use (`fs.readFileSync(filePath)`), and it works.

What does this have to do with the client?

**Comment by trs** [comment]
Changing the `root` for the client determines what they see.

If the server has a directory structure:
```
/
/hello
/hello/world
/hello/world/one
/hello/universe
/hello/universe/one
```
And I set a client's `root` to `/hello/world`. So they would see their directory as `/`, even though it is in a different place on the server. If they changed directory to `./one`, the server's directory would be `/hello/world/one`, but the client's directory would be `/one`.

Because the client's root is `/hello/world`, they would not be able to access anything `/hello/universe`, and they wouldn't even know about it.

So for the `STOR` server event, you'd be correct in sending the "real" server path.
But if we wanted to respond with the full path to the client, we'd want the client's path.

**Comment by DiegoRBaquero** [comment]
Yes, I understand. But the event is emitted on the server, I always meant it server side (get the full path) to read it on the server.

**Comment by trs** [comment]
We could use `stream.path` then to get were the stream is being written to.

**Comment by mutour123** [comment]
![screenshot from 2018-08-13 15-48-43](https://user-images.githubusercontent.com/19345200/44019127-7987e0a2-9f10-11e8-8d0f-2d326d2ca052.png)

Why do I print this content?

**Comment by trs** [comment]
@mutour123 The error states it cannot find the file at that path. Does it exist?
